KafkaServer {
  org.apache.kafka.common.security.scram.ScramLoginModule required
  username="kafka-broker-2"
  password="broker-2-secret";
};

Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="zk-client-secret";
};
