bootstrap.servers=localhost:29092,localhost:39092,localhost:49092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="limited" password="limited-secret";