Server {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_zookeeper="zk-server-secret"
  user_kafka="zk-client-secret";
};

QuorumServer {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="zookeeper"
  password="zk-server-secret";
};

QuorumLearner {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="zookeeper"
  password="zk-server-secret";
};
